namespace: heart-disease-mlops

replicaCount: 2

image:
  repository: heart-disease-api
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: heart-disease.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

probes:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
