apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heart-disease-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "heart-disease-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "heart-disease-api.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "heart-disease-api.fullname" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: 8000
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: 8000
            initialDelaySeconds: {{ add .Values.probes.initialDelaySeconds 5 }}
            periodSeconds: {{ add .Values.probes.periodSeconds 10 }}
